namespace AppServicesTests;

using AppServices;

public class MazeSolverTests
{
    [Fact]
    public void SolveVerySimpleMaze()
    {
        var parsedMaze = new ParsedMaze("SXO\nOOO\nXOE");

        //SXO
        //OOO
        //XOE

        var solver = new MazeSolver();
        var (solutionSteps, difficulty) = solver.SolveMaze(parsedMaze);

        Assert.Equal("D,R,D,R", solutionSteps);
        Assert.Equal(1.97, difficulty, 2);
        Assert.True(WalkThroughMaze(parsedMaze.Content, solutionSteps));
    }

    [Fact]
    public void SolveOpen10X10Maze()
    {
        var parsedMaze =
            new ParsedMaze(
                "SOXOXOOOOX\nOOOOOOOXXO\nOXXOXOXOOO\nOOOXOOOXXO\nOOOOOXOXOO\nOXXXOXOOOX\nOOOXOXXOXO\nXOOXOOXXOO\nXOOXOOXOOO\nOOXXOOOOXE");

        var solver = new MazeSolver();
        var (solutionSteps, difficulty) = solver.SolveMaze(parsedMaze);

        //reachable deadends 8, totallength 65

        Assert.Equal(8.59, difficulty, 2);
        Assert.True(WalkThroughMaze(parsedMaze.Content, solutionSteps));
    }

    [Fact]
    public void SolveOpen10X10MazeWithDifferentStartingPoint()
    {
        {
            var parsedMaze = new ParsedMaze(
                "XOXOXOOOOS\nOOOOOOOXXO\nOXXOXOXOOO\nOOOXOOOXXO\nOOOOOXOXOO\nOXXXOXOOOX\nOOOXOXXOXO\nXOOXOOXXOO\nXOOXOOXOOO\nOOXXOOOOXE");

            var solver = new MazeSolver();
            var (solutionSteps, difficulty) = solver.SolveMaze(parsedMaze);

            //reachable deadends 7, totallength 65

            Assert.Equal(8.31, difficulty, 2);
            Assert.True(WalkThroughMaze(parsedMaze.Content, solutionSteps));
        }
    }

    [Fact]
    public void Solve100X100MazeWithDifferentStartingPoint()
    {
        {
            var parsedMaze = new ParsedMaze(
                "OOXXXOOXXSOOOXXXOOOOXXXXOXOOOXXOOOOXXOXXXXXXXXXOXXOXOXXXOOXOXXXOOXXXXOXXOOXXXXXOXXXOOOOXOOOXXXOXOXOO\nXXXXXOXXOOXOOOOXXOOOOOXOXOOOOXXOOXOOOXOOOOXOOXXOOOXXOOXXXOXXOOXOOXOOXOOOXOOXOXOXOXOOXXXOOXOOOXOOXOXO\nOXOOXXXXXXOOOXOOOOXOXOXOOOOOOOOOXOOXOOXXOXOOOXOOOOXOXOXOXOOOXXXXXOOOOXOXXXOOOXOOOXXXOXOOXOOXOOXOOOXO\nOXOOOXXXOXOXOXOXXOXXOOOOXOXOXXXXOXOXOOOOXXXOOOXOXXXOXXOOOOXXOOXXXOXOOXOOOOOXOOOOXXXXXXOOOXOOOXOXXXOX\nOOXOOOXOXXOXOOXOOXXOOOOOOOOXOOOOXOOOXXOXXXXOXXXXOXOXXOOXOOXOOXOOXXOOOOOXOOOXXXXOOOOOOOOOXOOOXOXXOOXX\nXXXXOOOXOXXOXOOXOXOXXXOXXXOXOOOOXOXXOXOXOOOXOOXOXXOXOOOXOOOOOOOXOOOOOXOXOOOOOOOXOXOOXOOXXXOOXXXXOOOX\nOOXXOXOOOOOOOOOOOOOOOXOXXOXOOOOOXOOXXOOXXXOXOXXOXOOOOOOOXOOOOOOXXOOOOOOOOXOXOOOXOOXXOOOXXXXXXXOXXXOO\nOXOOXOXOXXOOXOOXOOOXOXOOXOOOOOXXOOXOOOXOOXXXOOOXOXOXOOXXOXOOXXOOXOXXOOXXOOXOXOXOOXXOXOOOOOOOOOOOOXOX\nXOOOOOOOOOXXXOOOOXOOOOOOXXXXXXXOOOOOOOOOOOOOOOOOOOXXOXXOXXOOXOOOOXXXOXXOOXOOXOOXXXOXXOXOOXOXXOOXOXOO\nOOOOOXOOXOXXOXXOXXOOXOOOXXOOOOOXOXOOOOOOOOXXOOOXOOXXOXOOXOXOOOXOOXXOXOOXOOOOXOOOOXOOOXOOOOOXOXXOOOXX\nXOOXOOOOOOOOXXOXOXOOOXOXXOOOXOXOXOOOOOOOXOXOXOOOXXOXOOOOOOOXXOOOOOXOOOOXXOXXXXXXOXXXXOOOXOXOOOOOOOXX\nOXOXXOOXXXOOXOXXXOOOXOOOOOXOXOOXXOOOOXOXXOOOOXOXOXOXOXXOOOXOOOOOOOOOOOOOOXOOOOXOOXXXOOOOOXOOXXOOOOOO\nOXOOOXXOOOOOOOXXOOXOXOOOOXOOOXOOXXOXOXXOXOOXXXOOXOXOOOOOOOXOXOXOOXOOOOOXOXOXOOOOOXXOXOOOXXOOXOXXOOXX\nXOXOOOOOOOOOXXXXOXOXXXOXOOXOXOOOXOOOXXXXXOXOOOOOXXXXXOXXOOXOOOOOOXOOOOOOXXOOOXOOOXOOOXOOOXOOXXOOOXOX\nXOOOOOXOOOXOOXXOOOXXOXXOOOXOOXOOXXXOXOXOXOOXXOOXOXOXXOOXOXXXXXXOOOOOOOXXOXXOOXOOOXXOOOOOOXOXOXOOOOXO\nXOXXXOXOOOOOOXXXXOXOXOXOOOOOOXOOOXOXOOOXXOXOOXOXXXOOOOXOOOOXOOXXXXOXOXXOXXOOXXXXXOXXOOOXOXXOXXXOXOOO\nOXOXXXOOOOXOXXOXOXOOXOXXOOXXOXOOOOOOOXXOXXOXXOXXXXOOOOXOOXOOXOOOXOOOXOXXXOOOXOXOOOOOXOOOXXXOOOXOOOXX\nXXOXXOOOXXOOOOOXOXXOOOOXOOOOOOOXOXOXOOOOOOOOOXOXOOOXOOOOOOOOXXOOOXXOXOOXOXXXXOOOOXOOOXOOOXOXOOOXOXXX\nOOXOXOOXXXOXOOOOOOOOOOXXOXXOOOOOXOOOOXOXOXXOOXXXOOOOOOOXOXOXXOOOOOOXOOOXOXXXOOOOOXOOXOXOXOOOOOXOOOXO\nXXOXXXXXXXOOOOXXXXXOXXOXXXOOXOOOOOXOOOOOOXOXOOXOXOOXOOOXXOOOOXOOXOOOOXOOOXXXOOXOOOOXXOOXOXOXOOXXXOOO\nOOXOXOXXOXOOXXXOOOOOOOXXOOOXXOOOXOOXOOXXOOOXOOOOOXOOXXXOXOXXOXOOOXOOOOOOXOOXOXOOOOOOXXOOXXXOOOOOOXOX\nOOXOOOXOOXOXOXOOOXXXOOXOOOXOOOOXOOXXOOOOOOXOXOOOXOXOXOOOXOXXXOOXOOOXOXXOXXXOOOXOXOXOXXXXOOXOOOOXXXXO\nXXOOOXXOXXOOOOOOOOOOXOOXXOXXOXOOXOXOOOXXOOOOOOXOOOOOXOOOOOOXOOOOOXXXOXOXOOOOOOXOXOOXOOXOOOOXOXXXOOOO\nXXXOXOXOOOXXOXXXXOOOOOXOXOXXOOOOOOOOXOOOOOOXOOOOOOOOOXOOXOXOXOXXOXXOOXOXOOOOOXOXXOOOOOXOXXOOOOOXXOXX\nOOXOOOXOXXXXXOXOXOOOXXOOOXOOXOXXOXOXOOOXOOOXOOOOXOOXOXXOXOXOOOOXOXXOXXOOXXXOOXOXXXXXOOXOXXOXOOOXOOOO\nXXXXXOXOXOXXXXOXXXOOOOOXXOOXOOOOOOOXXXXXOOOXXOOOXXOOXOXOXXXXOOXXOXOOXOXXOXOOXOOXOOOXOOOOOXOOXOOOXXOX\nXXXOXOOOOOOOXOOXXOOXXOXXOXOOXXXOOOOOXXXOXXXXOOOOOOOOOXOOXXXOXOOOXOOXOOOOOOOXOXXOOXOOXOXOOXOXXOOXOXOX\nOOOOOOOXXOXOOXXOOOOOXXXOXOOXOOOXXXOOOOOXOXXXXOOXXXOOOOXOXOOOXOOOXOOOXXOOXXXXXXOOOOOOXXOXOXOXXXXOOOXO\nOOOOXOXOOOOXXOOOOOOOXXOOOOOXXXOXOXOXOXOXXOOXOXOXOOXOXOXOXOXXXOOOXXOOXOOOOXOOOOXOOXOOXXXOOOOOOXOOXXOX\nOXOOOXOOOOXXOOOXOXXOXXOOOOOOOOXOOXOOXOOOXXOXOOOXOOOOOOOOXOXXOOOXOXOOOOOOOXOXOOOOXOOOXXOOXOOOOOXOOXOO\nXOOOXOOXXOOOXXOOOOOXOOXXXOXOXOOXXXOXOXOOOOOOOXOXOXXOOOOOOOOXOOXXXOXOOOXXXXOXOOOXXOXOOOOOXXOXOXXXXXOO\nOOOXXXOOXOOXXXXOOOOXXOOOOXOOOOOOXOXXXOOOOXOOXOXOXOOOOXOXXXXXOOOOOOXXXXOOXXOOXXOXOOOXXOOOOXOOOOOXOOOO\nOOOXXOOXOOOXOXXOOXOOOXOOXOOOXXOXOOOXOOXXOOXOXOXOXXOXXXOXXOOOOOXOOOOOXXXOOOOXXOOXOXXOOXXOXOOOOOXOXOXO\nXXOXXOXOOOXOXOOOOXOOOOOOOOOXXOOOXOXXOXOXOXXOXXOOXOXXOOXXOOOOOXOOOOXXXOOOXOOXOXOXOOOOOOXOOOOXOXOXOXOO\nOOXOOOOOXOOXXXOXOXOOXOOOOOXXXOOOXOOOXXOOXXOOXXOXOXOOOXOXOOOXOOOOXOXOOXOXOOXOXOXXOOOOOXXOOOOOOXXOOOOO\nXXXXOOOOOOOXXOOOXOXXOXOXOOOOOOOOXOXOOXXOXXXXOXOOOXOXOXOXXXOOXXXXOOXOXOXOXOXOXOXOOOOOXOXXOXOXOOOXXOXO\nOOOOOOOXXOXXOOXOXOXXOXOXXXXOOOXXOOOOXXOXOOOXXXOOOOOOOXXOOXOOOOXXXOOXXOOXOOXOXOXXOOOOXOXXOOOOOXOXOOXX\nXXXXXOOXXXOXXXXOOXOXOOOOOOOOXOXXOXOXXXOOOXXXXOOOOOOOXOOOXOOOXXXXOXOOXOOOOXOOOOXXXXOXOOXOOXOOOXOOXOXX\nXOXOXOOOOOXOOXXOOOOOXOXOXXOOOOOOXOXOOOOOOOXOXXOXOOOXOOXOOXOXXOOOXXOOXOXOOXOOXXOOOOOXOOOXOOOOXOOXOOOO\nOOXOXXXOOOXOOXXOOOOOOXXOXOOOOOOOOOXOXOOOXXOXOXOXOOOXXOXOOOOOOXOXOOOOOOXOOOOOOOXOOOOXXOOOOXXOXXXXXXOX\nOXXXOOOXOOXOOXXOOOOXXOXOXOOOOOXOXOXOOXOOXXXXXXOOXOXOXXXOOOOOXOOXXOOOOXXOXXXOOXXOXOOOXOXXOXOXOOOXXOOO\nOOXOOOXOXXOOXOOXOXXOOOOOOOOOOOOXOOXXOOOOOXOOXOXOOXOXOXXOXOOOOOXXOOXOOOOOOOXXOOXOOOOOXOOOOXXXOXOOXOOO\nOOOOOOOOOOXOXXOOOOXOXOXXOXOOXXXXOOXXOXOXOOOOXOOOOXXOXXXOOOXOXXOOOXXOOXOXOXXOXOXXXXXXOOOOOOOXXOXOOOXX\nXXOXXOOXOOXXXOXOXOXOXOXXOOXXOXXOOXOXOOOOOOOXXOOOOOOXOXOOOOXOOOOOXOOOOOXXOXOOXXOXOOOOOOOXXXXOOXXOXOOO\nOXOOXOXOXXOOOOOXXXXOOOOOOXOXXOOOOXOOOXXXOOOXOOXOXOOXOXOOOXOXOOXOOXXOOXXOOOOXOXOXOOOXXOOXXOXOXOXOXOOO\nXOXXOOXOOOOXOOXXXXXXXOXOXOOOOXOXOXXXOOOXXXOOXOOOOXOXXXXXXOOXXXOXOOXOOOOXOXOXXOOXOOXOOOXOOOXXXXXXXOOO\nOOXOOOOXOXXOXOXOOXOOOOOOOXOXXOOOXOOXOOXXOXXXOOXOXOXXXXOXOOXOOOOOOOXXOXOOOXOOOOOOXOXOOOXXOOOOXOXXXOOX\nOOOOOOXOOOOOXXXOXOOOXOXXXXXXXXOOOOOXXXOOOOOXXOOXOOOOOXOOOOOXOOOXXOXOOOOXOOXOXXXOOOOOXOXOOOOOOOXOOOXO\nOOOOOOOOOXXOXXXOXXOXXOXOOXOXOOXOOOOXXXOOOOOOOOXOXXXOOXOOOOOOOOOOOOOOXXOXXXOOXOXOOOOOOOOOXOOOOOOOOOOO\nOOXXOXOOOOXOXXOOXOXOXXXOOXOOXOOOXOOXOOOOXOXXXOXXOXOXXXXOOOXOOOXXOOOOOOOOOOXXXXOXXXXXOOOOOOOXOXOOOOXO\nOOOXOXXXOOOXOXXOOXXOXXXOOOXOXOOXOOOOXOOOOXXOXXXXXXOXOXOOXXXOXOXOXOOXOOXOOXXXXOOOOOXXXXXXXOOXOXOXOXXO\nOXOOOXOOXOOXOOOXXXOOOXOXOXXOOXXOOXXOOOXOOOXOXXOXXOOOXOOXXXOOXXXXOOOOXOOOOOXXXOOOOOOXOXOXXXXXXOOXXXXX\nOOXOOXXXXOOXXOOXOXOXOOXXXOOOXOOXOOXOOOXOOOOXXOOXXOOXOOXOOOXOOXXOXOOOOOOOOXXOOXXOOXOOXOOOXOOOOXOOOXXX\nXOOXXOOOOOOOOOOXOOXOXOOXXOXXXOOOOOOXOOOOOXXXOOXOOOXOXOOXOOOOXXXOOXOOOOOOOOOXOXXXXOOOOXOOXXOXOXXOOXXO\nXOXOOXXXXOXXXOXOXOXOOOOXXXOOOOOOOXXOOOOXOOOOXOOOXOOXOOXOXOXOOXXXOOXXOXOOOOOXXOXOXOOXOXOXOOOOXXOOXOOX\nXOXOOOOOOXOXOOOXOXOOOOXOOXOOXXXOOOOXXOOOOOOOXOXOOOOXOXOXOOXOOXOXXOOOOXOOXOOOXOOXOOXOXXOOXOOOOXXOXOOX\nXXXXOXOOXOOXXXOOOOXXXXOXOXXXOOOOXXOOOOXXXOXXOXOOOXOOXXXXOOXXXOXOXXXOXOOXOOOXOXOOOOOXOXXOOOXOOOXOOXXO\nOOXOOOOOXXXXXOOXOOXXOXXXOOOXOXOOXOOXOOOXOOOOOXOOXOOOXOOOOOXOXXOXOXOOOOOXXOOOOXOXXOXXXOOOXXOOOXXXOOXO\nXXOOXOOOOXOXXXXOXOOOOXXOXOOOOOXXOOOXOOOXXXOOXXOOXOXOOOOXOXOOOOOOOOOXXOOXOOOOOXOOXXOOXOXXXOXOXXOOXXXX\nOXXXXOXXXXXOOOXOXXXXOOXOOXOOOOXOXXXXOOOXOXOOOOOOXOXOOOOXOOOXXOOOOXXOXOOOOOOOOXOOXXXXOOOXXXXXOOXOOXXX\nOOOOOOXXXXOOOOXOOOOXOXXXXXOXOXXXXOXOOOXOXOXXOOXXXOXOOOOOXOXOXOOOXXOXOOXXOXXOOXOOOOOXOXOXOOXXXXOXXXOX\nOXXOXXXXOXOXOOOOOOXOOOOXXXOXOOXOOXOOXXOOXXOOOXXOOOXOXOOOOXOXXOOOOXOOOOOOOXOXOOOXOXOOOOXOOOXXOOOXOOOO\nOOXOXOXXOXOOOOXXXOXOOXOOOOXXOOOOXOOXOOOOXXOXOXOXXOXOOXOOOXXOOOOOOXOOXOXXOOXOXOXXXXOOXXXXOXOOOOXXOXOO\nOOOXOOXXOOXOXOOXXOXOOOOOXOOOXOOXOOOOXOXOOOXOOOOXOOXXOXOXOOXXOOXXOOXOXOXOXOOXOOXXOXOXOOXOOXOXOXOXOXOO\nOXXOOOOXOOOXOOXXOXOXOOOOXXOOOXOOOXOOXXXOOXOXOOXOXOOOOOXXXXOOXOXOOXOOXOXOOOXOOOXOOXOXOOOXOOXOOOOXXOXX\nXXOOOXOOXOOOXXOOOOOOOXXOXOOOXXXXXOXOXXOOOXOXOOOOOOXXOXOOXXOXXXOXXOOOOXOOXXOOXXOOXXOOOXOOOOOXOOOOOOOX\nOOOOXXOOXOOXXOXOXXOXXOOXOXXOOXOOXOOXOXXOOOOOOXXOOOOXXOXOOOXOOOXXOOOOXOXOOOOXXOOOXOXOXOOOOXOXXOOOOXXO\nOOOOXXXXOOOOOOOXOXXOOOOOXXOXXXOXOOOOOOOXOXXXOXXOXOOXXOOOOOXXOOXOOOOOOOOOOXXXOOOXOXXOXOOOOOOOXXOOXOXO\nXOOXOOOOXXOXOOOXOXXXOXOXOOOOOOXOOOXXXOOXOXXOOOXOOXOOXOXOXOOXXXXOXXOXOXXOXOXOXOOXOXOXOXXOOXXOXOXOOXOO\nXOOOXXOXOXOXXOOXOOXOOXXOXOOOOOOOXOOOOXXOOXXXXXXOXOXOXOOXOOXXOOXOOOOXOOOOOOOOOOOXOOXXOXOOXOXXOOOOOXOO\nXOXOXOXOXOXOXXOXOXXXOXOOOXOOXOXOXXOOXOOOXOXOOOXOXXXOOOOXOOOOOOOOOXOOXOXOOXXOXXOXXOXOOOXOXOXOOOXOOOXO\nXXOOXXXOXOOOOOOOXOXOXXOXOOXOXOOXOOXXXOXXOOXOOOOOXXOOOXXOXOOOXXXOOOOXOXOXXOXOOXXXOXOOXXOOXXXOXOXXOXOX\nOOXOOXOOXOXOXOXOOXOOOXOOXOXOOXXOXOXOXOXOOOOOXXOOXXOXOOOOOOOOXOOXOOOXXOOXXXOXOXOXXOOOOOOOXXXOXOXXOOXO\nOXXOOXXOOOXOOXOOOXOOOOOOOOXOOXXXXOOOXXOXOOOOXOOOOOOOOOXOOXXXXOOOXXXXOOOOOXOXXOOOOXOXOOXOOOOXXOXXOXOO\nXOXXXOXOOXOOXXXXOOOOXOXOXXOOXXOOOXOOXXXXXXOOXOOXOXXOOOOOOXXOXXOOOOOXOXOOOOOOOOOXOOXOXOXOOOOOXXOXOXOO\nXOOXXOXXXOXOOOXOXOOXOXOOOOOXOOXOXOXXOXOXOOOOOOXXXXXOOOXOOOXOXOOOOOXOOOOOXXOOOOXXOXXOOOOOOXXXXXXOXOXX\nOXXOXXOOXOXOOXOOOXXXOOXOOOOXXOXOOXOOOOOXXOXOXOOXXXXXOOOOXOOXOXOXXXOXOXXOOXXXOOXOXOOOOXOXOOOOOXXOXXXO\nOXOOXXXXOXXXOOXXOOOOOOOOOXXOOXXOXOOOXOOXOXXOOXXOXXXOXXOOOOXXXOXXXOOOOXXOOXXOOOOOOXOOXOXXOOOXOOXXXOXX\nXOXOOXOXXXXOXXXOXXXOOOXOXOXOXXOOOOOXOOXOXOOOOOXXXXOOOXOXXOOOXXOXOOXOOXXOXXOOXXXOOOXXOOOOOOXXOXOXXOXO\nOOOXXOOOOOXOOXOOOOOOOOOXOOXXOOOOXXOOOXOOOXOXXXOOXOXXOXXXOOXXOOOXXOOOOOOOOXXOOOOOXOOOXOOOXOOOXOOXOOOO\nOXOOXOXOXXXOOXXXOOOOXOXXXXOOXXXXOXOOOXOOXOOOXXOOXOXOOXOOXOOXXOOXOOOXOOOOXXOOOOOOXOXXOOXOOOOOOOOOXOOO\nXOOOXOXOOOOOXOOXOXXXOXXXOOOOOOXXOXOXOOXXOXOOXXOOOXOOOOOOOOOXOXOOOOXOXOXXXXOXOXOOOOOXXOOOXOOOOOOXOXXO\nXOOOOOOXOOXXXXOOOOOXOXOOOXOXOOOOOXOOXOXXOOOOXXOXXOXXOXOOOXOOXOOOXOOOOOOXXOXXXOXOOOOXXXOOXOOOOOXXOXOO\nOXOXXXOXXOOOXXXOOOXOOOOXXOOOXXXOOOOXOOOXOOOOXXOOOOXOXOOXXOXOOXOOOOOOXOOOOOXOXXOXXXXOOOOOXOXXOOOXXOXO\nOXXOOXOXOOOXOXXOOOXOOOXOOXXXXOOOXXOXOOXXOOXOOOOOXXOXOXOOOOOXXOOOOXOXOXOXOOOXOOOOOOXXXOXOOOOXOOXOOOOO\nOOXOOOOOXOOOOXOOOOXXXXOOOXXXOXOXOOOXOXOOXOOOXOOOXOOOXOOOOOXXXXXXXOXOXOOOXOXOOOOXOOXOXOOXXXXXOXXOOXOO\nOOOOOXOOOXXXOOOOXXXOOOOOXOOOXXXOOXOOXOXOOXOXOXXXOOOXXXOOOOXOOOXXOOXOXXOOOXOXXOOXOOXOOOOOOXOOOXXOOXXX\nOOOOXXXOXXXXOOXOOOOXXOXOXXOOOOXXXOOOOXOOXOXXOXOOXOXXOOOOOOOOXOOXOXXOXXXOXXXOXXOOXXOXOXOXOOOOOOOOOXXO\nXOOOOOXXOXOXOOOOXOOOOOXOOXXOOOOXXXOOOOOXXXXXOXOXOOXXOXOXOOOXOOOOOXOOOXOOOXOXOOOOOOOXXOOXOOOXOOOOOOOO\nXOXOOOOXXXOOOOOOOOXOOOXOXOOXXXOOOXXOOXXOXOOXOXXXXXXXOXOOOOXOXXXXOOOOOOOXXOOXXXOOOOXOXOXOXOXOOOXXXOXO\nOOOXOOOOOOXOXOXOXXOOOOOOOOOOOXOXOOXXOXXOOOOXXOOOXOOXXOXOOOXOXOXOXXOXXOOXOXOXXXOXXXOOOOXXOOXXOOOOXOXX\nXOXOXOOOOXOOXOOXOOOOOXOOOOXXOXOOOXXOOOOOXOXOXXOXOOXOOOOOOOOOXXXOXXXOOOXOOOOXXXXXOXXXOOOXOXXOXXOOXXXO\nXXXXXOXOXXOOOOOXOOXXXOOOOXXOXOXOXXXOOXOXOXXOOOXOOOXXXOOOXOXOXOXXXOXXOXXOOOOOOXOXXOOOOOOOOOOXOXOOXOXO\nXXXOXOXXXXOOOXOOOXOOXOOOOOOOXXOOOXOOXXOXOOXXOOOOXXOOXOOOOXXXOOXXXXOOOXXXOOOOOXXOOXOOXXXXOXXOXOOXOXXO\nOOXXXOXOXXOXXXOOOOXXOOOXOXOXOOXOXOXOXOOOXOOOXXOXOXXOOOOOXOXOOOOXXXOOOXXXOOXXOXOOOOOOOXOXOXXOXOOXOOOX\nXXXXOXOXOOXOOOXXOXOOOOOOOOXXXXOXOOOXXXOXXXOXXOOOOXOOOOOOXOOXXOXOXOXXXOXOXOOXOOOOXOOOOXOXXXOOOOXOXXOX\nXOOOXXXXOXOOOXXOOOXXXXOOOOOOXXXOOXXOXXOXOXXXOXOOOOOOXOOXOOOOXOOOOOOOOOXOOOXXOOOOOXOOOOOOXOOOOXXOXXXO\nOXOOOOOXOOXXXOOXXOXXXOXXOOXOOOOOXOXOOOXXOXXOOOOOOOOOXOOOOOXOOXOXOOOXOOXXXOOOOOOXXOXOOXXXXOXXOOOOOXOO\nOXOOOOXOOOOXOXXOXOXOOOXOOOOOXOXOOOOXOOXXOOOOOXOOXOOOOXOXXXXOXXXOOXXXOXXOOXOOOOOOOOOOXXXOXXXOXXOOOOOO\nXXOXOOOOOOOOXOXXOXOOOXOOXOXOXXOOOXOXOOXXXOXXOXXOOOOOXOOOXOXOOXXXOOXXXXXOOXXXOOOOXXOOXOOXOOOOOXOOOOOE");

            var solver = new MazeSolver();
            var (solutionSteps, difficulty) = solver.SolveMaze(parsedMaze);

            //reachable deadends 500, totallength 3.813

            Assert.Equal(10.00, difficulty, 0);
            Assert.True(WalkThroughMaze(parsedMaze.Content, solutionSteps));
        }
    }


    private bool WalkThroughMaze(string mazeData, string solutionSteps)
    {
        var dim = mazeData.Split("\n");
        var steps = solutionSteps.Split(",");
        Index index = null;

        for (var i = 0; i < dim.Length; i++)
        {
            if (!dim[i].Contains('S')) continue;
            var y = i;
            for (var j = 0; j < dim[i].Length; j++)
            {
                if (dim[i][j] != 'S') continue;
                index = new Index() { Y = i, X = j };
                break;
            }

            break;
        }

        if (index is null)
        {
            return false;
        }

        var currentSymbol = dim[index.Y][index.X];


        try
        {
            foreach (var step in steps)
            {
                switch (step)
                {
                    case "D":
                        index.Y++;
                        break;
                    case "U":
                        index.Y--;
                        break;
                    case "R":
                        index.X++;
                        break;
                    case "L":
                        index.X--;
                        break;
                    default:
                        return false;
                }

                currentSymbol = dim[index.Y][index.X];
                if (currentSymbol == 'X')
                {
                    return false;
                }
            }
        }
        catch (IndexOutOfRangeException e)
        {
            return false;
        }


        return currentSymbol == 'E';
    }

    private class Index
    {
        public int X { get; set; }
        public int Y { get; set; }
    }
}