/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MazeDto } from '../../models/maze-dto';

export interface MazesUploadPost$Params {
      body: {
'file'?: Blob;
}
}

export function mazesUploadPost(http: HttpClient, rootUrl: string, params: MazesUploadPost$Params, context?: HttpContext): Observable<StrictHttpResponse<MazeDto>> {
  const rb = new RequestBuilder(rootUrl, mazesUploadPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MazeDto>;
    })
  );
}

mazesUploadPost.PATH = '/Mazes/upload';
