/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { MazesUploadPost$Params as MazesUploadPost$Params } from './fn/mazes/mazes-upload-post';
export { mazesUploadPost as mazesUploadPost } from './fn/mazes/mazes-upload-post';
